apiVersion: v1
kind: Service
metadata:
  name: {{ include "cursos-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p8" }}
  labels:
    {{- include "cursos-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cursos-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
