{{- $global := .Values.global | default (dict) -}}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gateway-health
  namespace: {{ $global.namespace | default "sa-p8" }}
spec:
  metrics:
    - name: gateway-health
      interval: 10s
      count: 3
      failureLimit: 0
      successCondition: 'result == "ok"'
      provider:
        web:
          url: "http://{{ include "gateway.fullname" . }}-canary.{{ $global.namespace | default "sa-p8" }}.svc.cluster.local:{{ .Values.service.port }}/health"
          timeoutSeconds: 5
          jsonPath: "{$.status}"
