{{- if .Values.serviceAccount.create }}
{{- $global := .Values.global | default (dict) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ $global.namespace | default "sa-p8" }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
