global:
  namespace: sa-p6

replicaCount: 2

image:
  repository: acrsa201901385.azurecr.io/gateway
  tag: "p6"
  pullPolicy: IfNotPresent

fullnameOverride: "gateway"

service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000

config:
  PORT: "3000"
  AUTH_SERVICE: "http://auth-service:3001"
  CURSOS_SERVICE: "http://cursos-service:3002"
  INSCRIPCIONES_SERVICE: "http://inscripciones-service:3003"
  ESTUDIANTES_SERVICE: "http://estudiantes-service:3004"
  LOG_LEVEL: "info"

secret:
  name: "sa-platform-secrets"

serviceAccount:
  name: "gateway-sa"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 192Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1

probes:
  startup:
    path: /health
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 12

  readiness:
    path: /health
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3

  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
