apiVersion: v1
kind: Secret
metadata:
  name: sa-platform-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque

stringData:
  # Variables usadas por nuestros microservicios
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}

  RABBITMQ_USERNAME: {{ .Values.secrets.RABBITMQ_USERNAME | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD | quote }}

  # Claves requeridas por el chart Bitnami PostgreSQL
  postgres-password: {{ .Values.secrets.DB_PASSWORD | quote }}
  password: {{ .Values.secrets.DB_PASSWORD | quote }}

  # Claves requeridas por RabbitMQ
  rabbitmq-password: {{ .Values.secrets.RABBITMQ_PASSWORD | quote }}
  rabbitmq-erlang-cookie: {{ .Values.secrets.RABBITMQ_ERLANG_COOKIE | quote }}