apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace | default "sa-p5" }}
  labels:
    {{- include "cursos-service.labels" . | nindent 4 }}
automountServiceAccountToken: false
