apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-platform-db-init
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Files.Get "files/init.sql" | nindent 4 }}