apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inscripciones-service.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default "sa-p8" }}
  labels:
    {{- include "inscripciones-service.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
