# Datos de la entrega de la Practica 8.
CARNET="201901385"
REPO_CODE="https://github.com/BillyDread1531/Practicas-SA-B-201901385"
REPO_GITOPS="https://github.com/BillyDread1531/Practica-SA-P8-GitOps"
APP="sa-platform-dev"
NS="sa-p8"
IMAGE="acrsa201901385.azurecr.io/gateway:1.0.4"

COSIGN_IDENTITY_REGEXP="https://github.com/BillyDread1531/Practicas-SA-B-201901385/.*"
COSIGN_ISSUER="https://token.actions.githubusercontent.com"
