CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cursos (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  creditos INTEGER
);

CREATE TABLE IF NOT EXISTS inscripciones (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  curso_id INTEGER NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(50) DEFAULT 'ACTIVA'
);

CREATE TABLE IF NOT EXISTS estudiantes (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  apellido VARCHAR(150) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  carnet VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS eventos_inscripciones (
  id SERIAL PRIMARY KEY,
  inscripcion_id INTEGER NOT NULL,
  usuario_id INTEGER NOT NULL,
  curso_id INTEGER NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  procesado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cron_ejecuciones (
  id SERIAL PRIMARY KEY,
  carnet VARCHAR(50) NOT NULL,
  fecha_hora TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cron_resumenes (
  id SERIAL PRIMARY KEY,
  hora TIMESTAMP NOT NULL,
  total_ejecuciones INTEGER NOT NULL,
  recibido_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);